# Generated by Django 4.0.4 on 2022-05-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='pictures/%Y/%m/%d/', width_field='width'),
        ),
    ]
