# Generated by Django 4.0.4 on 2022-05-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
