# Generated by Django 4.0.4 on 2022-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_alter_picture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_blog',
            field=models.BooleanField(default=False, verbose_name='Is it a blog?'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Would you like to show it?'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='text',
            field=models.TextField(blank=True, verbose_name='Add a description'),
        ),
    ]
