# Generated by Django 4.0.4 on 2022-06-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_blog',
            field=models.BooleanField(default=False),
        ),
    ]
