# Generated by Django 4.0.4 on 2022-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_is_active_alter_gallery_is_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='is_blog',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='text',
            field=models.TextField(blank=True, verbose_name='Add a description'),
        ),
    ]
